import { defineType, defineField } from "sanity";

const pricingTierFields = () => [
  defineField({ name: "tag", title: "Tag (Sub-Label)", type: "string", validation: (Rule) => Rule.required().max(60) }),
  defineField({ name: "tagline", title: "Tagline", type: "text", rows: 2, validation: (Rule) => Rule.required().max(240) }),
  defineField({ name: "price", title: "Price (per seat / mo)", type: "number", validation: (Rule) => Rule.required().integer().min(1).max(9999) }),
  defineField({ name: "includesHead", title: "Bullets Heading", type: "string", validation: (Rule) => Rule.required().max(60) }),
  defineField({
    name: "bullets",
    title: "Included Bullets",
    type: "array",
    of: [{ type: "string", validation: (Rule) => Rule.max(120) }],
    validation: (Rule) => Rule.required().min(4).max(10),
  }),
  defineField({ name: "ctaLabel", title: "CTA Button Label", type: "string", validation: (Rule) => Rule.required().max(32) }),
  defineField({ name: "ctaHref", title: "CTA Button URL", type: "string", initialValue: "/contact", validation: (Rule) => Rule.required() }),
  defineField({ name: "flagLabel", title: "Flag Chip (Optional)", type: "string" }),
];

export const pricingTiers = defineType({
  name: "pricingTiers",
  title: "Pricing Tiers",
  type: "object",
  fields: [
    defineField({
      name: "eyebrow",
      title: "Eyebrow",
      type: "string",
      initialValue: "Plain-spoken pricing",
      validation: (Rule) => Rule.required().max(40),
    }),
    defineField({ name: "heading", title: "Heading", type: "headline", validation: (Rule) => Rule.required() }),
    defineField({
      name: "deck",
      title: "Deck",
      type: "text",
      rows: 3,
      initialValue:
        "All prices per seat per month, billed monthly. No setup fees, no after-hours surcharges, no ticket caps. Organizations over 100 seats are custom-priced — same model, different math.",
      validation: (Rule) => Rule.required().max(320),
    }),
    defineField({
      name: "essentials",
      title: "Essentials",
      type: "object",
      fields: pricingTierFields(),
      initialValue: {
        tag: "For small teams · 5 – 25 seats",
        tagline: "For small teams that just need the lights to stay on. Helpdesk, monitoring, and patching — flat-rate.",
        price: 125,
        includesHead: "What's in it",
        bullets: [
          "24/7 endpoint monitoring",
          "Unlimited helpdesk · SLC engineers",
          "Patch & vulnerability management",
          "MFA enforcement on admin accounts",
          "Monthly summary report",
          "Vendor management (Comcast, M365, etc.)",
        ],
        ctaLabel: "See if it fits",
        ctaHref: "/contact",
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "standard",
      title: "Standard",
      type: "object",
      fields: pricingTierFields(),
      initialValue: {
        tag: "Most popular · 15 – 100 seats",
        tagline: "Where most SMBs land. Managed IT plus the cybersecurity baseline we'd want on our own environment.",
        price: 165,
        includesHead: "Everything in Essentials, plus",
        bullets: [
          "EDR-grade endpoint protection",
          "Email security · anti-phishing · DMARC",
          "Conditional access policies",
          "Daily-verified backup restores",
          "Quarterly access reviews",
          "CIS v8 baseline alignment",
        ],
        ctaLabel: "Schedule a discovery call",
        ctaHref: "/contact",
        flagLabel: "★ Most clients land here",
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "premier",
      title: "Premier",
      type: "object",
      fields: pricingTierFields(),
      initialValue: {
        tag: "Strategic · 25 – 150 seats",
        tagline: "For organizations that have outgrown a part-time admin and need strategy, not just support.",
        price: 215,
        includesHead: "Everything in Standard, plus",
        bullets: [
          "Quarterly QBR with the founder",
          "Annual IT budget · built bottom-up",
          "90-day rolling roadmap",
          "Live risk register",
          "Cyber-insurance evidence pack",
          "Vendor renewal negotiation",
        ],
        ctaLabel: "Talk to the founder",
        ctaHref: "/contact",
      },
      validation: (Rule) => Rule.required(),
    }),
  ],
  preview: { prepare: () => ({ title: "Pricing Tiers" }) },
});
