import { defineType, defineField, defineArrayMember } from "sanity";

export const page = defineType({
  name: "page",
  title: "Page",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Internal Title",
      description: "Used in the Studio listing. Not rendered on the site.",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      description: "URL path. Use 'home' for the homepage.",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "seoTitle",
      title: "SEO Title",
      description: "Used in the <title> tag. Falls back to internal title.",
      type: "string",
      validation: (Rule) => Rule.max(60),
    }),
    defineField({
      name: "seoDescription",
      title: "SEO Description",
      description: "Meta description. Falls back to site default.",
      type: "text",
      rows: 2,
      validation: (Rule) => Rule.max(160),
    }),
    defineField({
      name: "ogImage",
      title: "Open Graph Image",
      description: "Falls back to site default.",
      type: "image",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alternative Text",
          type: "string",
          validation: (Rule) => Rule.required(),
        }),
      ],
    }),
    defineField({
      name: "blocks",
      title: "Page Blocks",
      description: "Compose the page from blocks.",
      type: "array",
      of: [
        defineArrayMember({ type: "darkNumbersHero" }),
        defineArrayMember({ type: "trustStrip" }),
        defineArrayMember({ type: "teamGrid" }),
        defineArrayMember({ type: "headaches" }),
        defineArrayMember({ type: "savings" }),
        defineArrayMember({ type: "servicesList" }),
        defineArrayMember({ type: "beliefs" }),
        defineArrayMember({ type: "ctaCard" }),
        defineArrayMember({ type: "pageHero" }),
        defineArrayMember({ type: "originPhoto" }),
        defineArrayMember({ type: "storyThreeCol" }),
        defineArrayMember({ type: "numbersStrip" }),
        defineArrayMember({ type: "milestonesTimeline" }),
        defineArrayMember({ type: "officeCulture" }),
        defineArrayMember({ type: "industriesContent" }),
        defineArrayMember({ type: "industriesDontSeeYours" }),
        defineArrayMember({ type: "contactBody" }),
        defineArrayMember({ type: "postList" }),
        defineArrayMember({ type: "servicesIndexHero" }),
        defineArrayMember({ type: "pricingTiers" }),
        defineArrayMember({ type: "bundleGrid" }),
        defineArrayMember({ type: "processStrip" }),
        defineArrayMember({ type: "industryCrosslink" }),
        defineArrayMember({ type: "switchingHero" }),
        defineArrayMember({ type: "switchingReasons" }),
        defineArrayMember({ type: "switchingTimeline" }),
        defineArrayMember({ type: "switchingHandle" }),
        defineArrayMember({ type: "switchingCompare" }),
        defineArrayMember({ type: "switchingPromises" }),
        defineArrayMember({ type: "switchingTestimonial" }),
        defineArrayMember({ type: "faqList" }),
      ],
      options: {
        insertMenu: {
          groups: [
            {
              name: "heroes",
              title: "Heroes",
              of: ["darkNumbersHero", "pageHero", "servicesIndexHero", "switchingHero"],
            },
            {
              name: "editorial",
              title: "Editorial",
              of: [
                "storyThreeCol", "headaches", "beliefs", "originPhoto", "officeCulture",
                "milestonesTimeline", "numbersStrip",
                "switchingReasons", "switchingHandle", "switchingPromises", "switchingTestimonial",
              ],
            },
            {
              name: "pricing",
              title: "Pricing & Process",
              of: ["pricingTiers", "bundleGrid", "savings", "processStrip", "switchingTimeline", "switchingCompare"],
            },
            {
              name: "trust",
              title: "Trust & Team",
              of: ["teamGrid", "trustStrip", "servicesList"],
            },
            {
              name: "industries",
              title: "Industries",
              of: ["industriesContent", "industriesDontSeeYours", "industryCrosslink"],
            },
            {
              name: "blog",
              title: "Blog & FAQ",
              of: ["postList", "faqList"],
            },
            {
              name: "cta",
              title: "Contact & CTA",
              of: ["contactBody", "ctaCard"],
            },
          ],
        },
      },
    }),
  ],
  preview: {
    select: { title: "title", slug: "slug.current" },
    prepare: ({ title, slug }) => ({
      title,
      subtitle: slug ? `/${slug}` : "(no slug)",
    }),
  },
});
